apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.MYSQL_ROOT_PASSWORD | b64enc | quote }}
  MYSQL_USER: {{ .Values.secrets.MYSQL_USER | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.secrets.MYSQL_PASSWORD | b64enc | quote }}
